### ISSUE TITLE
IndicesExists panics if index don't exist

### ISSUE THREAD

**Issue by meskio** [mattbaird/elastigo#91]
If the index I check with IdicesExists exist it works fine, but if it don't exist I get a panic. See sample code:

```
package main

import (
    "github.com/mattbaird/elastigo/api"
    "github.com/mattbaird/elastigo/indices"
    "fmt"
)

func main() {
    api.Domain = "localhost"
    fmt.Println(indices.IndicesExists("existing_index"))
    fmt.Println(indices.IndicesExists("not_existing_index"))
}
```

The output of this program is:

```
true <nil>
panic: interface conversion: error is *json.SyntaxError, not api.ESError

goroutine 16 [running]:
runtime.panic(0x643b40, 0xc2080401c0)
    /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/mattbaird/elastigo/indices.IndicesExists(0xc208023ed8, 0x1, 0x1, 0xb, 0x0, 0x0)
    /home/meskio/dev/go/src/github.com/mattbaird/elastigo/indices/indicesExists.go:29 +0x1b0
main.main()
    /tmp/foo.go:12 +0x18c

goroutine 19 [finalizer wait]:
runtime.park(0x4130a0, 0x802570, 0x800809)
    /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x802570, 0x800809)
    /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/go/src/pkg/runtime/mgc0.c:2636 +0xcf
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 23 [IO wait]:
net.runtime_pollWait(0x7f5856df46c0, 0x72, 0x0)
    /usr/local/go/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc20802c060, 0x72, 0x7f5856df3418, 0xb)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:84 +0x34
net.(*pollDesc).WaitRead(0xc20802c060, 0xb, 0x7f5856df3418)
    /usr/local/go/src/pkg/net/fd_poll_runtime.go:89 +0x30
net.(*netFD).Read(0xc20802c000, 0xc208022000, 0x1000, 0x1000, 0x0, 0x7f5856df3418, 0xb)
    /usr/local/go/src/pkg/net/fd_unix.go:232 +0x30e
net.(*conn).Read(0xc20803c020, 0xc208022000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /usr/local/go/src/pkg/net/net.go:122 +0xd2
net/http.noteEOFReader.Read(0x7f5856df4798, 0xc20803c020, 0xc2080421b8, 0xc208022000, 0x1000, 0x1000, 0xc20804e170, 0x8, 0x404158)
    /usr/local/go/src/pkg/net/http/transport.go:1200 +0x50
net/http.(*noteEOFReader).Read(0xc20803e4e0, 0xc208022000, 0x1000, 0x1000, 0x10000000041bde8, 0xc20804e170, 0xc20804e130)
    <autogenerated>:115 +0xb5
bufio.(*Reader).fill(0xc2080043c0)
    /usr/local/go/src/pkg/bufio/bufio.go:97 +0x152
bufio.(*Reader).Peek(0xc2080043c0, 0x1, 0x0, 0x4, 0x1, 0x0, 0x0)
    /usr/local/go/src/pkg/bufio/bufio.go:132 +0xd1
net/http.(*persistConn).readLoop(0xc208042160)
    /usr/local/go/src/pkg/net/http/transport.go:779 +0x95
created by net/http.(*Transport).dialConn
    /usr/local/go/src/pkg/net/http/transport.go:597 +0x8dd

goroutine 17 [syscall]:
runtime.goexit()
    /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 24 [select]:
net/http.(*persistConn).writeLoop(0xc208042160)
    /usr/local/go/src/pkg/net/http/transport.go:882 +0x336
created by net/http.(*Transport).dialConn
    /usr/local/go/src/pkg/net/http/transport.go:598 +0x8f5
```

**Comment by autarch** [comment]
I think this issue has been fixed.

**Comment by meskio** [comment]
Sadly I'm not using elastigo since a while, I see the API has changed enough to take me more than 5 minutes run my tests again. I believe that you fixed, I'm fine if you want to close the issue.

Thank you for fixing it.
